#author: Lucas Avanzi - lavz97ms@gmail.com
version: '3.8'

services:

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer_lavz
    ports:
     - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data

  postgresql:
    image: postgres:16-alpine
    container_name: postgres_db_lavz
    environment:
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pgNetwork

  pgAdmin:  
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin123"
    ports:
      - "80:80"
    depends_on:
      - postgresql
    networks:
      - pgNetwork

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_db_lavz
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Admin123#
    ports:
      - "1433:1433"
    volumes: 
      - sqlserver_data:/var/lib/sqlserver/data

  mysql:
    image: mysql:8.3
    container_name: mysql_db_lavz
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: mydb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql 

  oracle:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle_lavz
    environment:
      ORACLE_PWD: 12345678
    ports:
      - "1521:1521"
    volumes:
      - "oracle_data:/opt/oracle/oradata"

  redis:
    image: redis
    container_name: redis_db_lavz
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:latest
    container_name: mongo_db_lavz
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 12345678
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mynet0

  mongo-express:
    image: mongo-express 
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: 12345678
      ME_CONFIG_MONGODB_URL: mongodb://admin:12345678@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: mongo
      ME_CONFIG_BASICAUTH_PASSWORD: 123456
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    networks:
      - mynet0

volumes:
  portainer-data:
  postgres_data:
  sqlserver_data:
  mysql_data:
  oracle_data:
  mongo_data:

networks:
  mynet0:
    driver: bridge
  pgNetwork:
    driver: bridge

# arquivo de referencia:
# https://dev.to/jao_dev/docker-para-iniciantes-criando-containers-de-bancos-de-dados-291i
